### ISSUE TITLE
Change request for `x-command` behaviour 

### ISSUE THREAD

**Issue by scaljeri** [daveosborne/brackets-vimderbar#43] opened 2015-06-08 07:09 UTC
I noticed that the `x-command` behaves differently from Vim in my terminal.
For example, considered the following line of text

    Lorem ipsum dolor sit amet, consectetur adipiscing <cursor>elit

Note that the cursor is at `<cursor>` :)
Now, when I press (and hold it down) `x` what will happen is that it will delete the character following the cursor (in this case `elit`). If these are deleted, it will continue  with the character preceding the cursor, but this is not what happens with vimderbar. Vimderbar only deletes character after the cursor. 

I don't know is this is intended, but I would really like to see that the `x` command also delete character preceding the cursor as well. Is this possible ?

**Comment by daveosborne** [comment] 2015-07-04 20:10
Brackets is dependent on CodeMirror for all of the vim functionality, it looks like this has been fixed in upstream CodeMirror as it works at http://codemirror.net/demo/vim.html 

This should work in Brackets 1.4 whenever it is released, I'll leave this bug open until it's confirmed fixed.

**Comment by daveosborne** [comment] 2015-07-28 12:41
Fixed in Brackets 1.4

**Closed by daveosborne** 2015-07-28 12:41 UTC
Labels: bug
